CREATE TABLE IF NOT EXISTS workflow_runs (
    id CHAR(36) PRIMARY KEY,
    tenant_id BIGINT UNSIGNED NOT NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    workflow_id VARCHAR(128) NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    source_type VARCHAR(64) NULL,
    source_id VARCHAR(128) NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    state_version BIGINT UNSIGNED NOT NULL,
    checkpoint_schema_id VARCHAR(128) NOT NULL,
    checkpoint_schema_version BIGINT UNSIGNED NOT NULL,
    checkpoint JSON NOT NULL,
    steps_executed BIGINT NOT NULL,
    resume_count BIGINT NOT NULL,
    event_sequence BIGINT NOT NULL,
    max_steps BIGINT NOT NULL,
    max_resumes BIGINT NOT NULL,
    deadline DATETIME(6) NULL,
    claim_token VARCHAR(128) NULL,
    lease_until DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uk_workflow_runs_idempotency (tenant_id, owner_id, workflow_id, idempotency_key),
    KEY idx_workflow_runs_owner_status (tenant_id, owner_id, status, updated_at),
    KEY idx_workflow_runs_claim (status, lease_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workflow_waits (
    wait_id VARCHAR(128) PRIMARY KEY,
    run_id CHAR(36) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    wait_version BIGINT UNSIGNED NOT NULL,
    record_version BIGINT UNSIGNED NOT NULL,
    content_hash VARCHAR(128) NOT NULL,
    allowed_actions JSON NOT NULL,
    payload_ref VARCHAR(500) NULL,
    status VARCHAR(32) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    claim_token VARCHAR(128) NULL,
    lease_until DATETIME(6) NULL,
    resolved_action VARCHAR(32) NULL,
    resolved_actor_type VARCHAR(64) NULL,
    resolved_actor_id VARCHAR(128) NULL,
    resolved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT fk_workflow_waits_run FOREIGN KEY (run_id) REFERENCES workflow_runs(id) ON DELETE CASCADE,
    UNIQUE KEY uk_workflow_wait_run_version (run_id, wait_id, wait_version),
    KEY idx_workflow_waits_run_status (run_id, status, created_at),
    KEY idx_workflow_waits_pending (status, expires_at, lease_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workflow_node_events (
    run_id CHAR(36) NOT NULL,
    sequence BIGINT NOT NULL,
    workflow_id VARCHAR(128) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    run_status VARCHAR(32) NOT NULL,
    attempt BIGINT NOT NULL,
    resume_count BIGINT NOT NULL,
    wait_id VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    duration_ns BIGINT NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    PRIMARY KEY (run_id, sequence),
    CONSTRAINT fk_workflow_node_events_run FOREIGN KEY (run_id) REFERENCES workflow_runs(id) ON DELETE CASCADE,
    KEY idx_workflow_node_events_type_time (event_type, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
